#!/bin/bash
# 从本机 docker 容器 jx_m_apk_postgres 导出 jx_m_apk 库的种子数据
# 输出: frontend/public/db/seed.sql
# 用途: 给 PGlite 灌初始数据
#
# 用法: bash database/dump-jx-apk.sh
#
# 凭证: 必须从环境变量 PG_PASSWORD 传入, 不要在源码硬编码
#       例: set -a; source .env; set +a; bash database/dump-jx-apk.sh
#
# 说明: PGlite 不支持 pg_dump 的 SET/COMMENT/owner 等元数据语句,
#       所以先 --inserts 输出纯 INSERT,再用 sed 清理剩余的杂项。

set -e

PROJECT_DIR="/home/masterdododo/jxmapk"
OUT="$PROJECT_DIR/frontend/public/db/seed.sql"

# Docker 容器 + 连接参数
CONTAINER="jx_m_apk_postgres"
PG_USER="${PG_USER:-jx_m_apk_adu}"
PG_DB="${PG_DB:-jx_m_apk}"

# 密码必须从环境变量读, 不允许默认值
if [ -z "$PG_PASSWORD" ]; then
  echo "❌ 错误: 必须设置环境变量 PG_PASSWORD"
  echo "   例: set -a; source backend/.env; set +a; bash database/dump-jx-apk.sh"
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

echo "🔄 从 docker:$CONTAINER/$PG_DB 导出种子数据..."

# 1. 在容器内跑 pg_dump
#    --inserts: 输出 INSERT INTO ... VALUES (...) 形式(PGlite 友好)
#    --no-owner --no-privileges: 去掉 ALTER TABLE OWNER / GRANT
#    -t: 只导业务表 (排除 alembic / migrations / pgcatalog 等)
#    注: 不加 --data-only,这样会同时输出 CREATE TABLE / CREATE INDEX 等 schema
PG_DUMP_OUTPUT=$(docker exec "$CONTAINER" \
  bash -c "PGPASSWORD='$PG_PASSWORD' pg_dump \
    -U '$PG_USER' -d '$PG_DB' \
    --inserts --no-owner --no-privileges \
    -t 'jx_apk_*' -t pages -t page_versions -t published_pages" 2>&1)

if [ $? -ne 0 ]; then
  echo "❌ pg_dump 失败:"
  echo "$PG_DUMP_OUTPUT"
  exit 1
fi

# 2. 清理 PGlite 不兼容的语句
echo "$PG_DUMP_OUTPUT" | \
  sed -e '/^SET /d' \
      -e '/^SELECT pg_catalog/d' \
      -e '/^--/d' \
      -e '/^ALTER TABLE .* OWNER/d' \
      -e '/^ALTER TABLE .* ENABLE/d' \
      -e '/^COMMENT /d' \
      -e '/^\\./d' \
      -e '/^CREATE EXTENSION/d' \
      -e '/^GRANT/d' \
      -e '/^REVOKE/d' \
      -e '/^$/d' \
  > "$OUT"

# 3. 在文件顶部加注释 (PGlite 加载时跳过任何 CREATE EXTENSION 即可)
{
  echo "-- jx_m_apk seed data (auto-generated by database/dump-jx-apk.sh)"
  echo "-- generated at: $(date -Iseconds)"
  echo "-- PGlite 加载时需要先在 extensions 参数里传 pgcrypto 实例"
  echo ""
  cat "$OUT"
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"

LINES=$(wc -l < "$OUT")
SIZE=$(du -h "$OUT" | cut -f1)
INSERT_COUNT=$(grep -c "^INSERT INTO" "$OUT" 2>/dev/null || echo "0")

echo "✅ 导出成功"
echo "   文件: $OUT"
echo "   行数: $LINES"
echo "   大小: $SIZE"
echo "   INSERT 语句: $INSERT_COUNT 条"
